// Copyright (c) Demiurge Studios, Inc.
// 
// This source code is licensed under the MIT license.
// Full license details can be found in the LICENSE file
// in the root directory of this source tree.

namespace SlimCSLib.Generator
{
	public enum ScopeKind
	{
		/// <summary>
		/// Scope is a function type (method, local method, constructor).
		/// </summary>
		Function,

		/// <summary>
		/// Scope is a lambda expression.
		/// </summary>
		Lambda,

		/// <summary>
		/// Scope is a loop body (for, while, etc.).
		/// </summary>
		Loop,

		/// <summary>
		/// Switch ... case blocks.
		/// </summary>
		Switch,

		/// <summary>
		/// Scope is a method block, generated by LuaToCS to wrapper root file Lua code.
		/// </summary>
		TopLevelChunk,

		/// <summary>
		/// Scope is a try-catch-finally or using block. Certain control flow
		/// statements must be converted and handled specially within these
		/// blocks.
		/// </summary>
		TryCatchFinallyOrUsing,

		/// <summary>
		/// Scope is a type declaration (class, enum, etc.).
		/// </summary>
		Type,
	}
}
