-- This file was generated by SlimCS. DO NOT MODIFY.

if __initprogresssteps__ then __initprogresssteps__(3) end -- For startup progress tracking.
-- Concrete class file requires.
require 'Engine/Native/AnalyticsEvent'
require 'Engine/Native/Animation2D_BaseKeyFrame'
require 'Engine/Native/Animation2D_ClippingAttachment'
require 'Engine/Native/Animation2D_DataDefinition'
require 'Engine/Native/Animation2D_MeshAttachment'
require 'Engine/Native/Animation2D_PathAttachment'
require 'Engine/Native/Animation2DBenchmarks'
require 'Engine/UI/Animation2DNetwork'
require 'Engine/UI/Animation2DNetworkAsync'
require 'Engine/Engine/BigNumberFormatter'
require 'Engine/UI/Bitmap'
require 'Engine/Core/Bounds'
require 'Engine/Native/CommandLineArgWrapper_HString_'
require 'Engine/Native/CommandLineArgWrapper_String_'
require 'Engine/Native/CommandLineArgWrapper_UInt32_'
require 'Engine/UI/EditTextEvent'
require 'Engine/Core/EnumDescription'
require 'Engine/UI/Event'
require 'Engine/Native/Falcon_Stage3DShadowSettings'
require 'Engine/UI/FxDisplayObject'
require 'Engine/UI/Constants/FxFlags'
require 'Engine/Native/Game_AutomationScriptObject'
require 'Engine/Native/Game_ScriptMain'
require 'Engine/Native/Game_ScriptManagerProxy'
require 'Engine/Native/Game_VideoCapture'
require 'Engine/UI/GlobalBroadcastHandler/GlobalBroadcastHandler'
require 'Engine/Core/Globals'
require 'Engine/UI/Constants/HitTestMode'
require 'Engine/HTTP/LaneMasks'
require 'Engine/HTTP/Methods'
require 'Engine/HTTP/Results'
require 'Engine/HTTP/Status'
require 'Engine/UI/MovieClip'
require 'Engine/UI/Constants/InputEvents'
require 'Engine/Core/LoggerChannel'
require 'Engine/Core/Math'
require 'Engine/UI/MouseEvent'
require 'Engine/UI/Widgets/MovieScroller'
require 'Engine/UI/MusicPlayer/MusicPlayer'
require 'Engine/Core/Once'
require 'Engine/Core/Point'
require 'Engine/Native/Script_PseudoRandom'
require 'Engine/Native/ScriptAnimation2DManager'
require 'Engine/Native/ScriptAnimation2DQuery'
require 'Engine/Native/ScriptBenchmarkNativeTester'
require 'Engine/Native/ScriptBenchmarks'
require 'Engine/Native/ScriptEngine'
require 'Engine/Native/ScriptEngineAchievementManager'
require 'Engine/Native/ScriptEngineAnalyticsManager'
require 'Engine/Native/ScriptEngineCamera'
require 'Engine/Native/ScriptEngineCommerceManager'
require 'Engine/Native/ScriptEngineCore'
require 'Engine/Native/ScriptEngineFileManager'
require 'Engine/Native/ScriptEngineHTTP'
require 'Engine/Native/ScriptEngineHTTPRequest'
require 'Engine/Native/ScriptEngineInputManager'
require 'Engine/Native/ScriptEngineJobManager'
require 'Engine/Native/ScriptEngineLocManager'
require 'Engine/Native/ScriptEnginePath'
require 'Engine/Native/ScriptEnginePlatformSignInManager'
require 'Engine/Native/ScriptEngineProcess'
require 'Engine/Native/ScriptEngineRenderer'
require 'Engine/Native/ScriptEngineSettingsManager'
require 'Engine/Native/ScriptEngineSoundManager'
require 'Engine/Native/ScriptEngineTrackingManager'
require 'Engine/Native/ScriptEngineWordFilter'
require 'Engine/Native/ScriptMotion'
require 'Engine/Native/ScriptMotionApproach'
require 'Engine/Native/ScriptMotionPointToMove'
require 'Engine/Native/ScriptNetworkExtrapolator'
require 'Engine/Native/ScriptNetworkManager'
require 'Engine/Native/ScriptNetworkMessenger'
require 'Engine/Native/ScriptSceneObject'
require 'Engine/Native/ScriptSceneStateBinder'
require 'Engine/Native/ScriptSceneTicker'
require 'Engine/Native/ScriptUIAnimation2DNetworkInstance'
require 'Engine/Native/ScriptUIBitmapInstance'
require 'Engine/Native/ScriptUIEditTextInstance'
require 'Engine/Native/ScriptUIFxInstance'
require 'Engine/Native/ScriptUIInstance'
require 'Engine/Native/ScriptUIManager'
require 'Engine/Native/ScriptUIMovie'
require 'Engine/Native/ScriptUIMovieClipInstance'
require 'SlimCSBuiltins'
require 'Engine/Core/TableExtensions'
require 'Engine/UI/Constants/TweenTarget'
require 'Engine/UI/Constants/TweenType'
require 'Engine/Native/UI_Movie'
require 'Engine/Core/Vector2D'
require 'Engine/Engine/WordFilter'
require 'Engine/UI/EditText'
require 'Engine/UI/DisplayObject'
require 'Engine/Core/Protobuf'
require 'Engine/UI/RootMovieClip'
require 'Engine/Core/Utilities'
require 'Engine/Engine/AchievementManager'
require 'Engine/Engine/AnalyticsManager'
require 'Engine/Native/AppPCCommandLineArgs'
require 'Engine/Core/Native'
require 'Engine/Engine/Engine'
require 'Engine/Native/EngineCommandLineArgs'
require 'Engine/Engine/FileManager'
require 'Engine/Native/FilePath'
require 'Engine/Native/Game_Patcher'
require 'Engine/Game/GameMain'
require 'Engine/HTTP/HTTP'
require 'Engine/Engine/InputManager'
require 'Engine/Engine/LocManager'
require 'Engine/Engine/NetworkManager'
require 'Engine/Core/Path'
require 'Engine/Engine/PlatformSignInManager'
require 'Engine/Engine/Renderer'
require 'Engine/Engine/SettingsManager'
require 'Engine/Engine/SoundManager'
require 'Engine/Native/TimeInterval'
require 'Engine/Engine/TrackingManager'
require 'Engine/UI/UIManager'
require 'Engine/Native/WorldTime'
require 'Engine/Engine/CommerceManager'
require 'Engine/Game/DynamicGameStateData'
require 'Engine/Core/WorldTimeUtilities'
if __oninitprogress__ then __oninitprogress__() end

-- Initialization of concrete classes.
FinishClassTableInit(AnalyticsEvent)
FinishClassTableInit(Animation2D_BaseKeyFrame)
FinishClassTableInit(Animation2D_ClippingAttachment)
FinishClassTableInit(Animation2D_DataDefinition)
FinishClassTableInit(Animation2D_MeshAttachment)
FinishClassTableInit(Animation2D_PathAttachment)
FinishClassTableInit(Animation2DBenchmarks)
FinishClassTableInit(Animation2DNetwork)
FinishClassTableInit(Animation2DNetworkAsync)
FinishClassTableInit(BigNumberFormatter)
FinishClassTableInit(Bitmap)
FinishClassTableInit(Bounds)
FinishClassTableInit(CommandLineArgWrapper_HString_)
FinishClassTableInit(CommandLineArgWrapper_String_)
FinishClassTableInit(CommandLineArgWrapper_UInt32_)
FinishClassTableInit(EditTextEvent)
FinishClassTableInit(EnumDescription)
FinishClassTableInit(Event)
FinishClassTableInit(Falcon_Stage3DShadowSettings)
FinishClassTableInit(FocusEvent)
FinishClassTableInit(FxDisplayObject)
FinishClassTableInit(Game_AutomationScriptObject)
FinishClassTableInit(Game_ScriptMain)
FinishClassTableInit(Game_ScriptManagerProxy)
FinishClassTableInit(Game_VideoCapture)
FinishClassTableInit(GlobalBroadcastHandler)
FinishClassTableInit(Globals)
FinishClassTableInit(HitTestMode)
FinishClassTableInit(HTTPLaneMasks)
FinishClassTableInit(HTTPMethods)
FinishClassTableInit(HTTPResults)
FinishClassTableInit(HTTPStatusCodes)
FinishClassTableInit(InputEvents)
FinishClassTableInit(LoggerChannel)
FinishClassTableInit(Math)
FinishClassTableInit(MouseEvent)
FinishClassTableInit(MovieClip)
FinishClassTableInit(MovieScroller)
FinishClassTableInit(MusicPlayer)
FinishClassTableInit(NativeScriptUIMovieHandle)
FinishClassTableInit(Once)
FinishClassTableInit(PbMessageType)
FinishClassTableInit(Point)
FinishClassTableInit(RootMovieClip)
FinishClassTableInit(Script_PseudoRandom)
FinishClassTableInit(ScriptAnimation2DManager)
FinishClassTableInit(ScriptAnimation2DQuery)
FinishClassTableInit(ScriptBenchmarkNativeTester)
FinishClassTableInit(ScriptBenchmarks)
FinishClassTableInit(ScriptEngine)
FinishClassTableInit(ScriptEngineAchievementManager)
FinishClassTableInit(ScriptEngineAnalyticsManager)
FinishClassTableInit(ScriptEngineCamera)
FinishClassTableInit(ScriptEngineCommerceManager)
FinishClassTableInit(ScriptEngineCore)
FinishClassTableInit(ScriptEngineFileManager)
FinishClassTableInit(ScriptEngineHTTP)
FinishClassTableInit(ScriptEngineHTTPRequest)
FinishClassTableInit(ScriptEngineInputManager)
FinishClassTableInit(ScriptEngineJobManager)
FinishClassTableInit(ScriptEngineLocManager)
FinishClassTableInit(ScriptEnginePath)
FinishClassTableInit(ScriptEnginePlatformSignInManager)
FinishClassTableInit(ScriptEngineProcess)
FinishClassTableInit(ScriptEngineRenderer)
FinishClassTableInit(ScriptEngineSettingsManager)
FinishClassTableInit(ScriptEngineSoundManager)
FinishClassTableInit(ScriptEngineTrackingManager)
FinishClassTableInit(ScriptEngineWordFilter)
FinishClassTableInit(ScriptMotion)
FinishClassTableInit(ScriptMotionApproach)
FinishClassTableInit(ScriptMotionPointToMove)
FinishClassTableInit(ScriptNetworkExtrapolator)
FinishClassTableInit(ScriptNetworkManager)
FinishClassTableInit(ScriptNetworkMessenger)
FinishClassTableInit(ScriptSceneObject)
FinishClassTableInit(ScriptSceneStateBinder)
FinishClassTableInit(ScriptSceneTicker)
FinishClassTableInit(ScriptUIAnimation2DNetworkInstance)
FinishClassTableInit(ScriptUIBitmapInstance)
FinishClassTableInit(ScriptUIEditTextInstance)
FinishClassTableInit(ScriptUIFxInstance)
FinishClassTableInit(ScriptUIInstance)
FinishClassTableInit(ScriptUIManager)
FinishClassTableInit(ScriptUIMovie)
FinishClassTableInit(ScriptUIMovieClipInstance)
FinishClassTableInit(SlimCSStringLib)
FinishClassTableInit(TableExtensions)
FinishClassTableInit(UI_Movie)
FinishClassTableInit(Vector2D)
FinishClassTableInit(WordFilter)
FinishClassTableInit(DisplayObject)
FinishClassTableInit(EditText)
FinishClassTableInit(EventDispatcher)
FinishClassTableInit(ListenerCollection)
FinishClassTableInit(ListenerEntry)
FinishClassTableInit(NativeScriptUIMovieExtensions)
FinishClassTableInit(Protobuf)
FinishClassTableInit(RestoreEntry)
FinishClassTableInit(CoreUtilities)
FinishClassTableInit(AchievementManager)
FinishClassTableInit(AnalyticsManager)
FinishClassTableInit(AppPCCommandLineArgs)
FinishClassTableInit(CoreNative)
FinishClassTableInit(Engine)
FinishClassTableInit(EngineCommandLineArgs)
FinishClassTableInit(FileManager)
FinishClassTableInit(FilePath)
FinishClassTableInit(Game_Patcher)
FinishClassTableInit(GameMain)
FinishClassTableInit(HTTP)
FinishClassTableInit(InputManager)
FinishClassTableInit(LocManager)
FinishClassTableInit(NetworkManager)
FinishClassTableInit(Path)
FinishClassTableInit(PlatformSignInManager)
FinishClassTableInit(Renderer)
FinishClassTableInit(SettingsManager)
FinishClassTableInit(SoundManager)
FinishClassTableInit(TimeInterval)
FinishClassTableInit(TrackingManager)
FinishClassTableInit(UIManager)
FinishClassTableInit(WorldTime)
FinishClassTableInit(CommerceManager)
FinishClassTableInit(DynamicGameStateData)
FinishClassTableInit(WorldTimeUtilities)
if __oninitprogress__ then __oninitprogress__() end

-- Execution of static constructors.
Globals.cctor()
Protobuf.cctor()
CoreUtilities.cctor()
AchievementManager.cctor()
AnalyticsManager.cctor()
AppPCCommandLineArgs.cctor()
CoreNative.cctor()
Engine.cctor()
EngineCommandLineArgs.cctor()
FileManager.cctor()
FilePath.cctor()
Game_Patcher.cctor()
GameMain.cctor()
HTTP.cctor()
InputManager.cctor()
LocManager.cctor()
NetworkManager.cctor()
Path.cctor()
PlatformSignInManager.cctor()
Renderer.cctor()
SettingsManager.cctor()
SoundManager.cctor()
TimeInterval.cctor()
TrackingManager.cctor()
UIManager.cctor()
WorldTime.cctor()
CommerceManager.cctor()
DynamicGameStateData.cctor()
WorldTimeUtilities.cctor()
if __oninitprogress__ then __oninitprogress__() end